#!/bin/sh
#/etc/init.d/weatherService
#
# Based on: https://www.exratione.com/2013/02/nodejs-and-forever-as-a-service-simple-upstart-and-init-scripts-for-ubuntu/
#
### BEGIN INIT INFO
# Provides:       weatherService
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts weatherService
# Description:       starts weatherService using start-stop-daemon
### END INIT INFO
#

NAME="weatherService"
NODE_BIN_DIR="/usr/bin/node"
NODE_PATH="/usr/lib/node_modules"
APPLICATION_PATH="/home/pi/weather/app.js"
PIDFILE="/var/run/weatherService.pid"
LOGFILE="/var/log/weatherService.log"
MIN_UPTIME="5000"
SPIN_SLEEP_TIME="2000"

# Define AWC_DARK_SKY_API_KEY, AWC_HAS_INDOOR_SENSOR, AWC_NTP_SERVER, etc., in the file below:
[ -f /etc/default/weatherService ] && . /etc/default/weatherService

PATH=$NODE_BIN_DIR:$PATH
export NODE_PATH=$NODE_PATH
export AWC_ALLOW_CORS=$AWC_ALLOW_CORS
export AWC_DARK_SKY_API_KEY=$AWC_DARK_SKY_API_KEY
export AWC_DAYTIME_SERVER=$AWC_DAYTIME_SERVER
export AWC_FREQUENT_ID=$AWC_FREQUENT_ID
export AWC_HAS_INDOOR_SENSOR=$AWC_HAS_INDOOR_SENSOR
export AWC_LEAP_SECONDS_URL=$AWC_LEAP_SECONDS_URL
export AWC_NTP_SERVER=$AWC_NTP_SERVER
export AWC_PORT=$AWC_PORT
export AWC_TH_SENSOR_GPIO=$AWC_TH_SENSOR_GPIO

start() {
  echo "Starting $NAME"
  forever \
    --pidFile $PIDFILE \
    -a \
    -l $LOGFILE \
    --minUptime $MIN_UPTIME \
    --spinSleepTime $SPIN_SLEEP_TIME \
    start $APPLICATION_PATH 2>%1 > /dev/null &
  RETVAL=$?
}

stop() {
  if [ -f $PIDFILE ]; then
    echo "Shutting down $NAME"
    forever stop $APPLICATION_PATH > /dev/null 2>&1
    rm -f $PIDFILE
    RETVAL=$?
  else
    echo "$NAME is not running"
    RETVAL=0;
  fi
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: {start|stop|restart}"
    exit 1
    ;;
esac

exit $RETVAL
